# **Extraer la Data del CSV e Instalación de Librerías**

Fragmento para declarar e instalar la librerías que se implementaran en el notebook.

In [1]:
import pandas as pd

Importar la data del archivo CSV, indicando la ruta del archivo, y mostrar parcialmente su contenido.

In [2]:
data = pd.read_csv(filepath_or_buffer='./data/backloggd_indie_games.csv', encoding="UTF-8")
data

,Title,Developer,Release_Year,Avg_Rating,Plays,Rating_Count,Genres,Platforms,Avg_Time
0,Hollow Knight,Team Cherry,2017.0,4.4,181K,124K,"Adventure, Indie, Platform","Windows PC, Mac, Linux, Nintendo Switch 2, Pla...",59h
1,Undertale,tobyfox,2015.0,4.3,158K,106K,"Adventure, Indie, Puzzle, RPG","Windows PC, Mac, Linux, Nintendo Switch, PlayS...",16h
2,Hades,Supergiant Games,2020.0,4.2,156K,104K,"Adventure, Brawler, Indie, RPG","Windows PC, Mac, PlayStation 5, Xbox Series X|...",48h
3,Stardew Valley,ConcernedApe,2016.0,4.2,152K,93K,"Adventure, Indie, RPG, Simulator, Strategy","Windows PC, Mac, Linux, Nintendo Switch 2, Nin...",129h
4,Among Us,Innersloth,2018.0,3.1,149K,82K,"Indie, Strategy","Windows PC, PlayStation 5, Xbox Series X|S, Ni...",27h
...,...,...,...,...,...,...,...,...,...
48765,Cheated,Tbjbu2,2026.0,NaN,0.0,0.0,"Adventure, Indie, Simulator, Strategy",Windows PC,- h
48766,Outer Space Bar,OZNA STUDIO,2026.0,NaN,0.0,0.0,"Arcade, Indie",Windows PC,- h
48767,Astro Amigo,NaN,2026.0,NaN,0.0,0.0,"Adventure, Indie","Windows PC, Mac",- h
48768,PNR: Point of No return,NaN,2026.0,NaN,0.0,0.0,Indie,Windows PC,- h
48769,White Creek,Storybird Studio,NaN,NaN,0.0,0.0,"Adventure, Indie, Puzzle","Windows PC, Nintendo Switch 2, PlayStation 5, ...",- h

# **Limpieza de Datos**

Antes de eliminar las filas que impiden hacer el análisis, es necesario hacer transformaciones en los datos de las siguientes columnas del dataset:

- **Avg_Time**: El valor de las horas promedio para finalizar el juego, esta acompañado en una 'h' para indicar que el tiempo esta en horas. Para ello, se elimina ese caracter para trabajar esta columna en datos numericos.

- **Rating_Count y Plays**: El valor de estas columnas esta acompañado de una 'K' para indicar que el valor esta simplificado y se representa en miles. Entonces, se elimina ese caracter, cambiamos el tipo de dato a numerico y multiplicamos por 1000 para mantener el valor original.

In [3]:
def transfrom_val(value):

    if value[-1:] == 'K':
        value_str = value.replace('K', '')
        return float(value_str) * 1000

    return float(value)

In [4]:
for i, row in data.iterrows():

    rate_count = transfrom_val(row['Rating_Count'])
    plays = transfrom_val(row['Plays'])

    time = row['Avg_Time'].replace('h', '').replace('- ', '0')

    data.loc[i, 'Rating_Count'] = rate_count
    data.loc[i, 'Plays'] = plays
    data.loc[i, 'Avg_Time'] = float(time)

Se elimina aquellas filas que cumplen con las siguientes condiciones (las que se expresa en el siguiente fragmento de código):

- La fila tiene 1 o más valores nulos
- La cantidad de veces que se inicio sesion en un juego sea igual a 0.
- El contador de calificaciones sea igual a 0.
- El tiempo de promedio de horas ocupadas para terminar un juego sea 0 o no hay datos reportados.

In [6]:
data = data.dropna(subset=[
    'Developer',
    'Release_Year',
    'Avg_Rating'
])
data = data[data['Plays'] > 0]
data = data[data['Rating_Count'] > 0]
data = data[data['Avg_Time'] > 0]

data

,Title,Developer,Release_Year,Avg_Rating,Plays,Rating_Count,Genres,Platforms,Avg_Time
0,Hollow Knight,Team Cherry,2017.0,4.4,181000.0,124000.0,"Adventure, Indie, Platform","Windows PC, Mac, Linux, Nintendo Switch 2, Pla...",59.0
1,Undertale,tobyfox,2015.0,4.3,158000.0,106000.0,"Adventure, Indie, Puzzle, RPG","Windows PC, Mac, Linux, Nintendo Switch, PlayS...",16.0
2,Hades,Supergiant Games,2020.0,4.2,156000.0,104000.0,"Adventure, Brawler, Indie, RPG","Windows PC, Mac, PlayStation 5, Xbox Series X|...",48.0
3,Stardew Valley,ConcernedApe,2016.0,4.2,152000.0,93000.0,"Adventure, Indie, RPG, Simulator, Strategy","Windows PC, Mac, Linux, Nintendo Switch 2, Nin...",129.0
4,Among Us,Innersloth,2018.0,3.1,149000.0,82000.0,"Indie, Strategy","Windows PC, PlayStation 5, Xbox Series X|S, Ni...",27.0
...,...,...,...,...,...,...,...,...,...
18882,Dino Path Trail,Void Pointer,2025.0,1.9,7.0,5.0,Indie,Windows PC,1.0
19587,After You,k148 Game Studio,2020.0,2.3,6.0,6.0,"Adventure, Indie, Puzzle","Windows PC, PlayStation 5, Xbox Series X|S, Ni...",1.0
20025,Kernelbay,Nexent,2026.0,2.4,6.0,5.0,Indie,Windows PC,15.0
20068,Typical,TsunamiGames,2018.0,1.9,6.0,5.0,"Adventure, Indie, Visual Novel","Windows PC, Mac, Linux",16.0
20103,Crystal Story: The Hero and the Evil Witch,Emmanuel Salva Cruz,2020.0,2.5,6.0,6.0,Indie,"Windows PC, Android",6.0